function create_connectivity_figure(X1, X2, YMatrix1, YMatrix2, text, ttl)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2, YMATRIX3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 09-Jun-2020 16:44:50

% Create figure
figure1 = figure;
% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'MarkerSize',6,'Marker','+',...
    'LineWidth',3,...
    'LineStyle',':');
yl = ylim;
ylim([0, yl(2)]);
for i = 1:length(X2)
    set(plot1(i),'DisplayName', strcat(text, num2str(X2(i))));
end

ylabel('Коэффициент связности');

% Create title
title(ttl);

grid(subplot1,'on');

set(subplot1,'FontSize',14);
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.189650109276592 0.775 0.341162790697675]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes1,'MarkerSize',6,'Marker','+',...
    'LineWidth',3,...
    'LineStyle',':');
yl = ylim;
ylim([0, yl(2)]);
for i = 1:length(X2)
    set(plot2(i),'DisplayName', strcat(text, num2str(X2(i))));
end

% Create ylabel
ylabel('Эффективность');

grid(axes1,'on');
set(axes1,'FontSize',14);

% Create xlabel
xlabel('Скорость, м/с');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.521803289812022 0.880926682644261 0.379960311901948 0.0455298001896467],...
    'Orientation','horizontal', 'FontSize',14);
name=strcat(ttl, '.png');
set(gcf, 'Position', [0, 0, 1000, 600]);
saveas(gcf, name);
export_fig all_conn.png;
